name: My Github Actions Workflow
on: [push]

jobs: 
  testing_github:
    runs-on: ubuntu-latest
    steps: 
      - name: Hello
        run: echo "Hello, Github Actions!"
      - name: display repo name
        run: echo "this workflow is running in ${{ github.repository }}""
